---
title: "geom_boxplot"
author: "Ethel Ruan"
date: "2017-01-24"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


**Box and whiskers plot.**
          

##Usage
```
geom_boxplot(mapping = NULL, data = NULL, stat = "boxplot", position = "dodge", ..., outlier.colour = NULL, outlier.color = NULL, outlier.shape = 19, outlier.size = 1.5, outlier.stroke = 0.5, notch = FALSE, notchwidth = 0.5, varwidth = FALSE, na.rm = FALSE, show.legend = NA, inherit.aes = TRUE)

stat_boxplot(mapping = NULL, data = NULL, geom = "boxplot", position = "dodge", ..., coef = 1.5, na.rm = FALSE, show.legend = NA, inherit.aes = TRUE)
```

##Examples

```{r}
p <- ggplot(mpg, aes(class, hwy))
p + geom_boxplot() + geom_jitter(width = 0.2) + coord_flip()

p + geom_boxplot(notch = TRUE,
                 varwidth = TRUE,
                 fill = "white", colour = "#3366FF",
                 outlier.colour = "red", outlier.shape = 1)
                
p + geom_boxplot(aes(colour = drv))


ggplot(diamonds, aes(carat, price)) +
  geom_boxplot(aes(group = cut_width(carat, 0.25)))

y <- rnorm(100)
df <- data.frame(
  x = 1,
  y0 = min(y),
  y25 = quantile(y, 0.25),
  y50 = median(y),
  y75 = quantile(y, 0.75),
  y100 = max(y)
)
ggplot(df, aes(x)) +
  geom_boxplot(
    aes(ymin = y0, lower = y25, middle = y50, upper = y75, ymax = y100),
    stat = "identity"
  )
```
          

##See also

`stat_quantile` to view quantiles conditioned on a continuous variable
`geom_jitter`  for another way to look at conditional distributions.
