---
title: "geom_errorbarh"
author: "Ethel Ruan"
date: "2017-01-20"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#geom_errorbarh
`geom_errorbarh` 
**Horizontal error bars**
          

##Usage
```
geom_errorbarh(mapping = NULL, data = NULL, stat = "identity", position = "identity", ..., na.rm = FALSE, show.legend = NA, inherit.aes = TRUE)
```

##Description
Horizontal error bars

##Aesthetics
`geom_errorbarh` understands the following aesthetics (required aesthetics are in bold):
```
    x
    xmax
    xmin
    y
    alpha
    colour
    height
    linetype
    size
```
##Examples
```{r}
library(ggplot2)
df <- data.frame(
  trt = factor(c(1, 1, 2, 2)),
  resp = c(1, 5, 3, 4),
  group = factor(c(1, 2, 1, 2)),
  se = c(0.1, 0.3, 0.3, 0.2)
)

# Define the top and bottom of the errorbars

p <- ggplot(df, aes(resp, trt, colour = group))
p + geom_point() +
  geom_errorbarh(aes(xmax = resp + se, xmin = resp - se))
```
         

```{r}
p + geom_point() +
  geom_errorbarh(aes(xmax = resp + se, xmin = resp - se, height = .2))
```
        