---
title: "geom_abline"
author: "Ethel Ruan"
date: "2017-01-19"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


**Lines: horizontal, vertical, and specified by slope and intercept.**



##Usage

```
geom_abline(mapping = NULL, data = NULL, ..., slope, intercept, na.rm = FALSE, show.legend = NA)

geom_hline(mapping = NULL, data = NULL, ..., yintercept, na.rm = FALSE, show.legend = NA)

geom_vline(mapping = NULL, data = NULL, ..., xintercept, na.rm = FALSE, show.legend = NA)
```

##Examples

```{r}
library(ggplot2)

ggplot(mtcars, aes(wt, mpg)) + geom_point() +
  geom_vline(xintercept = 1:5,colour = "pink") + 
  geom_hline(yintercept = 20,colour = "blue") + 
  geom_abline(intercept = 20,size = 2) +
  geom_smooth(method = "lm", se = FALSE,colour = "green") 

mean_wt <- data.frame(cyl = c(4, 6, 8), wt = c(2.28, 3.11, 4.00))

ggplot(mtcars, aes(mpg, wt, colour = wt)) +
  geom_point() +
  geom_hline(aes(yintercept = wt, colour = wt), mean_wt) +
  facet_wrap(~ cyl)


```

###See also

See `geom_segment` for a more general approach to adding straight line segments to a plot.











































